default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: wishlist_web_db
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

